### ISSUE TITLE
Building jar doesn't work on Windows

### ISSUE THREAD

**Issue by NathanSmutz** [oakes/Nightcode#216] opened 2017-02-21 22:10 UTC
Im using the 2.3.0 .jar version on Windows 7.

I clicked build then ran the resulting file with "java -jar " and got a JNI error about not finding clojure/lang/IFn

Is Nightcode creating a jar or an uberjar?

Here's the error:
X:\smutzn\Documents\clojure-database-test\target>java -jar clojure-database-test
-0.0.1-SNAPSHOT.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/lang/IFn
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: clojure.lang.IFn
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

X:\smutzn\Documents\clojure-database-test\target>

**Comment by oakes** [comment] 2017-02-28 14:06
Ah yeah I started getting build errors on Windows recently, so now I package the exe version with a jar I built on OS X. Haven't tracked down why this is happening but it only happens on Windows.

**Comment by zooplankton** [comment] 2017-09-06 02:08
I think this is caused by JavaFX libraries on windows. The jar has to be packaged with javafxpackager instead of javapackager 

Please see https://stackoverflow.com/questions/16868446/javafx-exception-in-thread-main-java-lang-noclassdeffounderror-javafx-applica/18344096#18344096

**Comment by oakes** [comment] 2017-09-10 14:42
This was actually caused by the `uber` boot task not accounting for the fact that Windows uses backslashes as file separators. Fixed in 3bfd42cbe16b726fdb6cd530dad8398ab053cf86.

**Closed by oakes** 2017-09-10 14:42 UTC
